### ISSUE TITLE
US-20-1: Setup PostgreSQL-database in a suitable environment

### ISSUE THREAD

**Issue by LalaDK** [CPHB-KEPP/LSD#36]
Jeg har påbegyndt opsætning af et Docker-image, således at vi nemt kan distribuere database-serveren. Jeg synes som udgangspunkt at Docker virker som et super godt værktøj som vi bør anvende.

**Comment by philliphb** [comment]
Perfekt Mads.

Emilie, Kasper og Jeg har lige talt sammen og fundet ud af at vi ikke har behov for et script nok, derfor er den også blevet iceboxed.

Det vi nok kommer til at bruge istedet for et script er den måde Spring JPA Data persister dataen ned i databasen, derfor skal vi kun bruge et tomt skelet. Dvs. En tom PostgreSQL database med en user som vi kan tilgå den fra :)

Gerne instrukser om hvordan vi skal køre det fra serveren når den er klar :D

**Comment by LalaDK** [comment]
Modtaget :-) 

Jeg regner med at være færdig med et Docker-image med tilhørende instruktur i aften :-)
